# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f90c59b76624d19b19bb7d47b51531b788578917113d6efdcf01261ad99a20a8a264a4f87308d8bdc4b8e2eb8ce9f7c2b7c7b7539d775311235ddb19b0995ac6

test:
  secret_key_base: 5a79fb653d8b141d0fc528c5db7bb10914315ad3c5c24ab0692ad0e2db2705c62f0bcc7dad006aae74f76971cc6ad2baab9852d7f9ebb64ffbf3edb30efd9b54

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
